version: '3'
services:
  app:
    image: sloopstash/chef:v1
    container_name: crm-app
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    hostname: crm-app
    ports:
      - "8080:80"
    volumes:
      - /opt/kickstart-chef/supervisor/conf/main.conf:/etc/supervisord.conf
      - /opt/kickstart-chef/supervisor/conf/sshd.ini:/etc/supervisord.d/sshd.ini
      - /opt/kickstart-chef/supervisor/conf/chef-push-jobs-client.ini:/etc/supervisord.d/chef-push-jobs-client.ini
    extra_hosts:
      - "chef-server:100.3.1.0"
    depends_on:
      - redis
    networks:
      chef-net:
        ipv4_address: 100.3.1.10
  redis:
    image: sloopstash/chef:v1
    container_name: crm-redis
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    hostname: crm-redis
    volumes:
      - /opt/kickstart-chef/supervisor/conf/main.conf:/etc/supervisord.conf
      - /opt/kickstart-chef/supervisor/conf/sshd.ini:/etc/supervisord.d/sshd.ini
      - /opt/kickstart-chef/supervisor/conf/chef-push-jobs-client.ini:/etc/supervisord.d/chef-push-jobs-client.ini
    extra_hosts:
      - "chef-server:100.3.1.0"
    networks:
      chef-net:
        ipv4_address: 100.3.1.20
networks:
  chef-net:
    external:
      name: chef-net
